-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=magi1
TOOL_FOLDER_NAME=magi1
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="<img src="https://magifiles.nersc.gov/static/img/MAGI_logo.png" width="400"><br>MAGI 1<hr><a href='https://doi.org/10.1021/acschembio.8b01107'>Onur Erbilgin, Oliver Rübel, Katherine B Louie, Matthew Trinh, Markus DeRaad, Tony Wildish, Daniel Udwary, Cindi Hoover, Sam Deutsch, Trent R Northen, Benjamin P Bowen. MAGI: A Method for Metabolite Annotation and Gene Integration., ACS Chem Biol. 2019 Apr 19;14(4):704-714. doi: 10.1021/acschembio.8b01107. DOI: 10.1021/acschembio.8b01107 Epub 2019 Apr 4. PMID: 30896917.</a>"
